apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ark09/authentication
      context: authentication
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
manifests:
  rawYaml:
    - authentication/infra/k8s/ingress-srv.yaml
    - authentication/infra/k8s/authentication-depl.yaml
    - authentication/infra/k8s/authentication-mongo-depl.yaml