apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ark09/authentication
      context: authentication
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ark09/profile
      context: profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .            
manifests:
  rawYaml:
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/authentication-depl.yaml
    - infra/k8s/authentication-mongo-depl.yaml
    # - infra/k8s/profile-mongo-depl.yaml
    # - infra/k8s/profile-depl.yaml