apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-depl
  namespace: default
  labels:
    k8s-app: authentication-depl
spec:
  minReadySeconds: 9
  replicas: 1
  selector:
    matchLabels:
      k8s-app: authentication-depl
  template:
    metadata:
      name: authentication-depl
      labels:
        k8s-app: authentication-depl
    spec:
      containers:
        - name: authentication-depl
          image: registry.digitalocean.com/gogreen-repo/authentication
          securityContext:
            privileged: false
          env:
            - name: PORT
              value: "4000"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: builders-bid-cluster
            - name: MONGO_URI
              value: "mongodb://authentication-mongo-srv:27017/authentication"
            - name: NODE_ENV
              value: "development"
            - name: BODY_SIZE
              value: "10kb"
            - name: REQUEST_RATE_WINDOW
              value: "3600000" # 1 hour
            - name: MAX_REQUEST
              value: "100"
            - name: JWT_EXPIRY
              value: "864000" # 10 day in seconds
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RESET_SUPPORT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: reset-support-email
                  key: RESET_SUPPORT_EMAIL
            - name: MAIL_TRANSPORTER_USER_NAME_DEV
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-user-name-dev
                  key: MAIL_TRANSPORTER_USER_NAME_DEV
            - name: MAIL_TRANSPORTER_USER_PASSWORD_DEV
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-user-password-dev
                  key: MAIL_TRANSPORTER_USER_PASSWORD_DEV
            - name: MAIL_TRANSPORTER_USER_NAME_PROD
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-user-name-prod
                  key: MAIL_TRANSPORTER_USER_NAME_PROD
            - name: MAIL_TRANSPORTER_USER_PASSWORD_PROD
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-user-password-prod
                  key: MAIL_TRANSPORTER_USER_PASSWORD_PROD
            - name: MAIL_TRANSPORTER_HOST_DEV
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-host-dev
                  key: MAIL_TRANSPORTER_HOST_DEV
            - name: MAIL_TRANSPORTER_HOST_PORT_DEV
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-host-port-dev
                  key: MAIL_TRANSPORTER_HOST_PORT_DEV
            - name: MAIL_TRANSPORTER_HOST_PROD
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-host-prod
                  key: MAIL_TRANSPORTER_HOST_PROD
            - name: MAIL_TRANSPORTER_HOST_PORT_PROD
              valueFrom:
                secretKeyRef:
                  name: mail-transporter-host-port-prod
                  key: MAIL_TRANSPORTER_HOST_PORT_PROD
            - name: ALLOWED_ORIGINS
              value: "https://gogreen.rizsoft.online, https://gogreen.com, https://absolutely-sharp-llama.ngrok-free.app"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-srv
spec:
  selector:
    k8s-app: authentication-depl
  ports:
    - name: authentication
      protocol: TCP
      port: 4000
      targetPort: 4000
