apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: ark09/authentication
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: "mongodb://authentication-mongo-srv:27017/authentication"
            - name: NODE_ENV
              value: "development"
            - name: JWT_EXPIRY
              value: "864000" # 10 day in seconds
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-srv
spec:
  selector:
    app: authentication
  ports:
    - name: authentication
      protocol: TCP
      port: 4000
      targetPort: 4000
