apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: registry.digitalocean.com/gogreen-repo/chat
          env:
            - name: PORT
              value: "4005"
            - name: MONGO_URI
              value: "mongodb://chat-mongo-srv:27017/chat"
            - name: NODE_ENV
              value: "development"
            - name: BODY_SIZE
              value: "100kb"
            - name: REQUEST_RATE_WINDOW
              value: "3600000" # 1 hour
            - name: MAX_REQUEST
              value: "100"
            - name: JWT_EXPIRY
              value: "864000" # 10 day in seconds
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: ALLOWED_ORIGINS
              value: "https://www.gogreen.rizsoft.online, https://www.gogreen.com"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec:
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 4005
      targetPort: 4005
