apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: registry.digitalocean.com/gogreen-repo/file
          env:
            - name: PORT
              value: "4006"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: builders-bid-cluster
            - name: MONGO_URI
              value: "mongodb://file-mongo-srv:27017/file"
            - name: NODE_ENV
              value: "development"
            - name: BODY_SIZE
              value: "26mb"
            - name: REQUEST_RATE_WINDOW
              value: "3600000" # 1 hour
            - name: MAX_REQUEST
              value: "100"
            - name: JWT_EXPIRY
              value: "864000" # 10 day in seconds
            - name: BUCKET_NAME
              value: "gogreen-files-bucket"
            - name: FILE_URL_EXPIRES_TIME
              value: "86400"
            - name: BUCKET_REGION
              value: "ap-south-1"
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: access-key-secret
                  key: ACCESS_KEY
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-access-key-secret
                  key: SECRET_ACCESS_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: ALLOWED_ORIGINS
              value: "https://gogreen.rizsoft.online, https://gogreen.com, https://absolutely-sharp-llama.ngrok-free.app"
---
apiVersion: v1
kind: Service
metadata:
  name: file-srv
spec:
  selector:
    app: file
  ports:
    - name: file
      protocol: TCP
      port: 4006
      targetPort: 4006
