apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: gogreen.com
      http:
        paths:
          - path: /api/v1/users(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: authentication-srv
                port:
                  number: 4000
