apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: gogreen.com
      http:
        paths:
          - path: /api/v1/users(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: authentication-srv
                port:
                  number: 4000
          - path: /api/v1/profiles(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: profile-srv
                port:
                  number: 4001
          - path: /api/v1/(jobs|contracts|proposals|skills|categories)(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: job-srv
                port:
                  number: 4003
          - path: /api/v1/chats(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chat-srv
                port:
                  number: 4005
          - path: /api/v1/files(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: file-srv
                port:
                  number: 4006
