apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: job
          image: registry.digitalocean.com/gogreen-repo/job
          env:
            - name: PORT
              value: "4003"
            - name: MONGO_URI
              value: "mongodb://job-mongo-srv:27017/job"
            - name: NODE_ENV
              value: "development"
            - name: BODY_SIZE
              value: "300kb"
            - name: REQUEST_RATE_WINDOW
              value: "3600000" # 1 hour
            - name: MAX_REQUEST
              value: "100"
            - name: JWT_EXPIRY
              value: "864000" # 10 day in seconds
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: ALLOWED_ORIGINS
              value: "https://www.gogreen.rizsoft.online, https://www.gogreen.com"
---
apiVersion: v1
kind: Service
metadata:
  name: job-srv
spec:
  selector:
    app: job
  ports:
    - name: job
      protocol: TCP
      port: 4003
      targetPort: 4003
