apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: registry.digitalocean.com/gogreen-repo/profile
          env:
            - name: PORT
              value: "4001"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: builders-bid-cluster
            - name: MONGO_URI
              value: "mongodb://profile-mongo-srv:27017/profile"
            - name: NODE_ENV
              value: "development"
            - name: BODY_SIZE
              value: "150kb"
            - name: REQUEST_RATE_WINDOW
              value: "3600000" # 1 hour
            - name: MAX_REQUEST
              value: "100"
            - name: JWT_EXPIRY
              value: "864000" # 10 day in seconds
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: ALLOWED_ORIGINS
              value: "https://gogreen.rizsoft.online, https://gogreen.com, https://absolutely-sharp-llama.ngrok-free.app"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-srv
spec:
  selector:
    app: profile
  ports:
    - name: profile
      protocol: TCP
      port: 4001
      targetPort: 4001
