apiVersion: /app/v1
kind: Deployement
metadata:
  name: authentication-depl
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      lables:
        app: authentication
    spec:
      containers:
       - name: authentication
        image: ark09/authentication
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-srv
spec:
  selector:
    app: authentication
  ports:
    - name: authentication
      protocol: TCP
      port: 4001
      targetPort: 4001