const Subjects = {
  userCreated: "user:created",
  userUpdated: "user:updated",
  userDeleted: "user:deleted",
  userForgetPassword: "user:forgetPassword",
  userResetPassword: "user:resetPassword",
  productCreated: "product:created",
  productUpdated: "product:updated",
  productDeleted: "product:deleted",
  serviceCreated: "service:created",
  serviceUpdated: "service:updated",
  serviceDeleted: "service:deleted",
  orderCreated: "order:created",
  orderUpdated: "order:updated",
  orderDeleted: "order:deleted",
  jobCreated: "job:created",
  jobUpdated: "job:updated",
  jobDeleted: "job:deleted",
  proposalCreated: "proposal:created",
  proposalUpdated: "proposal:updated",
  proposalDeleted: "proposal:deleted",
  contractCreated: "contract:created",
  contractUpdated: "contract:updated",
  contractDeleted: "contract:deleted",
  fileUploadRequested: "file:upload-requested",
  fileUploadCompleted: "file:upload-completed",
  fileUploadFailed: "file:upload-failed",
  fileUploadDeleted: "file:upload-deleted",
};

module.exports = Subjects;
